# Form implementation generated from reading ui file 'new-new.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

class Ui_TypeWriter(object):
    def setupUi(self, TypeWriter):
        TypeWriter.setObjectName("TypeWriter")
        TypeWriter.resize(800, 600)
        TypeWriter.setMaximumSize(QtCore.QSize(16777215, 600))
        TypeWriter.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: none;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#mainFrame {\n"
"    background-color: #1b1929;\n"
"    border-radius: 28;\n"
"}\n"
"\n"
"#textInput {\n"
"    background-color: transparent;\n"
"    color: #a6adc8;\n"
"}\n"
"\n"
"#leftFrame {\n"
"    background-color: #1e1e2e;\n"
"    border-top-left-radius: 22;\n"
"    border-bottom-left-radius: 22;\n"
"}\n"
"\n"
"#rightFrame {\n"
"    background-color: #303045;\n"
"    border-top-right-radius: 22;\n"
"    border-bottom-right-radius: 22;\n"
"}\n"
"\n"
"#fontLabel {\n"
"    background-color: #585b70;\n"
"    color: #7f849c;\n"
"    border-radius: 6;\n"
"}\n"
"\n"
"#loadFontLabel {\n"
"    color: #585b70;\n"
"}\n"
"\n"
"#closeButton {\n"
"    background-color: #f38ba8;\n"
"    border-style: solid;\n"
"    border-radius:6px;\n"
"    max-width:12px;\n"
"    max-height:12px;\n"
"    min-width:12px;\n"
"    min-height:12px;\n"
"}\n"
"#minButton {\n"
"    background-color: #f9e2af;\n"
"    border-style: solid;\n"
"    border-radius:6px;\n"
"    max-width:12px;\n"
"    max-height:12px;\n"
"    min-width:12px;\n"
"    min-height:12px;\n"
"}\n"
"#maxButton {\n"
"    background-color: #a6e3a1;\n"
"    border-style: solid;\n"
"    border-radius:6px;\n"
"    max-width:12px;\n"
"    max-height:12px;\n"
"    min-width:12px;\n"
"    min-height:12px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=TypeWriter)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainFrame)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftFrame = QtWidgets.QFrame(parent=self.mainFrame)
        self.leftFrame.setMinimumSize(QtCore.QSize(280, 0))
        self.leftFrame.setMaximumSize(QtCore.QSize(280, 16777215))
        self.leftFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonFrame = QtWidgets.QFrame(parent=self.leftFrame)
        self.buttonFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.buttonFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.buttonFrame.setObjectName("buttonFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttonFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.closeButton = QtWidgets.QPushButton(parent=self.buttonFrame)
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.minButton = QtWidgets.QPushButton(parent=self.buttonFrame)
        self.minButton.setText("")
        self.minButton.setObjectName("minButton")
        self.horizontalLayout_2.addWidget(self.minButton)
        self.maxButton = QtWidgets.QPushButton(parent=self.buttonFrame)
        self.maxButton.setText("")
        self.maxButton.setObjectName("maxButton")
        self.horizontalLayout_2.addWidget(self.maxButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.buttonFrame, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.fontFileFrame = QtWidgets.QFrame(parent=self.leftFrame)
        self.fontFileFrame.setMinimumSize(QtCore.QSize(0, 70))
        self.fontFileFrame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.fontFileFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.fontFileFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fontFileFrame.setObjectName("fontFileFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fontFileFrame)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.loadFontFrame = QtWidgets.QFrame(parent=self.fontFileFrame)
        self.loadFontFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.loadFontFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loadFontFrame.setObjectName("loadFontFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.loadFontFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loadFontLabel = QtWidgets.QLabel(parent=self.loadFontFrame)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(14)
        self.loadFontLabel.setFont(font)
        self.loadFontLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.loadFontLabel.setObjectName("loadFontLabel")
        self.horizontalLayout_3.addWidget(self.loadFontLabel)
        self.verticalLayout_3.addWidget(self.loadFontFrame)
        self.openFontFrame = QtWidgets.QFrame(parent=self.fontFileFrame)
        self.openFontFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.openFontFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.openFontFrame.setObjectName("openFontFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.openFontFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fontLabelFrame = QtWidgets.QFrame(parent=self.openFontFrame)
        self.fontLabelFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fontLabelFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fontLabelFrame.setObjectName("fontLabelFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.fontLabelFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fontLabel = QtWidgets.QLabel(parent=self.fontLabelFrame)
        self.fontLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.fontLabel.setObjectName("fontLabel")
        self.horizontalLayout_5.addWidget(self.fontLabel)
        self.horizontalLayout_4.addWidget(self.fontLabelFrame)
        self.fontButtonFrame = QtWidgets.QFrame(parent=self.openFontFrame)
        self.fontButtonFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fontButtonFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fontButtonFrame.setObjectName("fontButtonFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.fontButtonFrame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4.addWidget(self.fontButtonFrame)
        self.fontButton = QtWidgets.QPushButton(parent=self.openFontFrame)
        self.fontButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/greyupload.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.fontButton.setIcon(icon)
        self.fontButton.setIconSize(QtCore.QSize(24, 24))
        self.fontButton.setObjectName("fontButton")
        self.horizontalLayout_4.addWidget(self.fontButton)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.openFontFrame)
        self.verticalLayout_2.addWidget(self.fontFileFrame)
        self.frame_2 = QtWidgets.QFrame(parent=self.leftFrame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2.addWidget(self.frame_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 380, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.frame = QtWidgets.QFrame(parent=self.leftFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.leftFrame)
        self.rightFrame = QtWidgets.QFrame(parent=self.mainFrame)
        self.rightFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.rightFrame)
        self.horizontalLayout_7.setContentsMargins(30, 50, 30, 30)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.textInput = QtWidgets.QPlainTextEdit(parent=self.rightFrame)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.textInput.setFont(font)
        self.textInput.setObjectName("textInput")
        self.horizontalLayout_7.addWidget(self.textInput)
        self.horizontalLayout.addWidget(self.rightFrame)
        self.verticalLayout.addWidget(self.mainFrame)
        TypeWriter.setCentralWidget(self.centralwidget)

        self.retranslateUi(TypeWriter)
        QtCore.QMetaObject.connectSlotsByName(TypeWriter)

    def retranslateUi(self, TypeWriter):
        _translate = QtCore.QCoreApplication.translate
        TypeWriter.setWindowTitle(_translate("TypeWriter", "MainWindow"))
        self.loadFontLabel.setText(_translate("TypeWriter", "Load Font"))
        self.fontLabel.setText(_translate("TypeWriter", "  C:/font/font.ttf"))
