# Form implementation generated from reading ui file 'splash_screen.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(300, 300)
        SplashScreen.setMinimumSize(QtCore.QSize(300, 300))
        SplashScreen.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(parent=SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container = QtWidgets.QFrame(parent=self.centralwidget)
        self.container.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.container.setObjectName("container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.circleBg = QtWidgets.QFrame(parent=self.container)
        self.circleBg.setStyleSheet("QFrame {\n"
"    background-color: #313244;\n"
"    color:  #cdd6f4;\n"
"    border-radius: 120;\n"
"    font: 9pt \"Segoe Ui\";\n"
"}")
        self.circleBg.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.circleBg.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circleBg.setObjectName("circleBg")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.circleBg)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.texts = QtWidgets.QFrame(parent=self.circleBg)
        self.texts.setMaximumSize(QtCore.QSize(16777215, 180))
        self.texts.setStyleSheet("background: none;")
        self.texts.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.texts.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.texts.setObjectName("texts")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.texts)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.fontFrame = QtWidgets.QFrame(parent=self.texts)
        self.fontFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.fontFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fontFrame.setObjectName("fontFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fontFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fontSelected = QtWidgets.QLabel(parent=self.fontFrame)
        self.fontSelected.setMinimumSize(QtCore.QSize(200, 24))
        self.fontSelected.setMaximumSize(QtCore.QSize(200, 24))
        self.fontSelected.setStyleSheet("QLabel {\n"
"    color: #a6adc8;\n"
"    border-radius: 12px;\n"
"    background-color: #6c7086;\n"
"}")
        self.fontSelected.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fontSelected.setObjectName("fontSelected")
        self.verticalLayout_4.addWidget(self.fontSelected, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout.addWidget(self.fontFrame, 2, 0, 1, 1)
        self.title = QtWidgets.QLabel(parent=self.texts)
        self.title.setMinimumSize(QtCore.QSize(0, 30))
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 0, 1, 1)
        self.percentFrame = QtWidgets.QFrame(parent=self.texts)
        self.percentFrame.setMinimumSize(QtCore.QSize(0, 60))
        self.percentFrame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.percentFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.percentFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.percentFrame.setObjectName("percentFrame")
        self.gridLayout.addWidget(self.percentFrame, 1, 0, 1, 1)
        self.loading = QtWidgets.QLabel(parent=self.texts)
        self.loading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loading.setObjectName("loading")
        self.gridLayout.addWidget(self.loading, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.texts)
        self.horizontalLayout.addWidget(self.circleBg)
        self.verticalLayout.addWidget(self.container)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "Loading"))
        self.fontSelected.setText(_translate("SplashScreen", "Font Selected:"))
        self.title.setText(_translate("SplashScreen", "Whiteboard Typerwriter"))
        self.loading.setText(_translate("SplashScreen", "loading..."))
